name: Build and Push CI Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/immortalwrt-firmware-builder-ci:latest
            ghcr.io/${{ github.repository_owner }}/immortalwrt-firmware-builder-ci:v${{ github.run_number }}

      - name: Delete workflow runs (best-effort)
        uses: Mattraks/delete-workflow-runs@main
        if: ${{ always() }}
        continue-on-error: true
        with:
          retain_days: 0
          keep_minimum_runs: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup-untagged:
    runs-on: ubuntu-latest
    needs: [ docker ]
    if: ${{ always() && github.event_name == 'workflow_dispatch' }}
    timeout-minutes: 15
    permissions:
      packages: write
    steps:
      - name: Delete UNTAGGED versions
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-type: container
          package-name: immortalwrt-firmware-builder-ci
          delete-only-untagged-versions: true