name: Build and Push Build Environment Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/immortalwrt-build-env:latest
            ghcr.io/${{ github.repository_owner }}/immortalwrt-build-env:v${{ github.run_number }}

  cleanup-untagged:
    runs-on: ubuntu-latest
    needs: [ build-and-push ]
    if: ${{ always() && github.event_name == 'workflow_dispatch' }}
    timeout-minutes: 15
    permissions:
      packages: write
    steps:
      - name: Delete UNTAGGED versions
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-type: container
          package-name: immortalwrt-build-env
          delete-only-untagged-versions: true