name: Cleanup

on:
  schedule:
    # Run every day at 3:00 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  cleanup-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs (action_required,cancelled,failure,skipped)
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          retain_days: 0
          delete_run_by_conclusion_pattern: 'action_required,cancelled,failure,skipped'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflow runs (success)
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          retain_days: 0
          keep_minimum_runs: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 3
          delete_tags: true
          delete_tag_pattern: '^immortalwrt-.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
